PlayerTracker/config/routes.rb
Rails.application.routes.draw do
  resources :teams do 
    resources :settings, only: [:show]
    resources :games
    resources :players
    get '/invite', to: 'teams#invite_new'
    post '/invite', to: 'teams#invite_create'
  end
  resources :players
  resources :games do
    get '/players/:player_id/track', to: 'tracker#track', as: 'track'
    get '/players/:player_id/show', to: 'tracker#show', as: 'track_show'
  end

  post '/create_tracks', to: 'tracker#create'
  
  devise_for :users

  get 'home/index'
  root 'home#index'
end

PlayerTracker/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :team
  has_many :trackers, dependent: :destroy

  validates :opponent, presence: true
  validates :date, presence: true
end

PlayerTracker/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :destroy]

  def show
  end

  def new
    @game = Game.new
    @team = Team.find(params[:team_id])
  end

  def create
    @team = Team.find(params[:team_id])
    @game = @team.games.create(game_params)
    respond_to do |format|
      if @game.save
        format.html { redirect_to team_path(@team) }
        format.json { render :show, status: :created, location: team_path(@team) }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to team_setting_path(@game.team), notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private 
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:date, :opponent)
    end
end

PlayerTracker/app/helpers/games_helper.rb
module GamesHelper
end

PlayerTracker/app/views/games/_form.html.erb
<%= form_with(model: [team, game], local: true, html: {class: "bg-white shadow-md  px-8 pt-6 pb-8 mb-4m"}) do |form| %>
  <div class="flex items-center py-2 text-blue-500 hover:text-blue-800 text-lg">
    Create Game
  </div>
  <div class="flex items-center border-b border-b-2 border-blue-500 py-2">
    <%= form.text_field :opponent, placeholder: "Opponent", class: "appearance-none bg-transparent border-none w-full text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none" %>
  </div>
  <div class="flex items-center border-b border-b-2 border-blue-500 py-2">
    <%= form.date_field :date, class: "appearance-none bg-transparent border-none w-sm text-gray-700 mr-3 py-1 px-2 leading-tight focus:outline-none" %>
  </div>
  <div class="mt-2">
    <%= form.submit "Create", class: "flex-shrink-0 bg-blue-500 hover:bg-blue-700 border-blue-500 hover:border-blue-700 text-sm border-4 text-white py-1 px-2 rounded" %>
    <%= link_to "Cancel", team_path(team), class: "flex-shrink-0 border-transparent border-4 text-blue-500 hover:text-blue-800 text-sm py-1 px-2 rounded" %>
  </div>
  <% if game.errors.any? %>
    <div id="error-explanation">
        <% game.errors.full_messages.each do |message| %>
        <p class="text-red-500 text-xs"><%= message %></li>    
        <% end %>
    </div>
  <% end %>
<% end %>

PlayerTracker/app/views/games/new.html.erb
<div class="flex mt-8 justify-center h-screen bg-indigo-100">
<div class="w-full max-w-md">
  <%= render 'form', game: @game, team: @team %>
</div>
</div>

PlayerTracker/app/views/games/show.html.erb
<div class="flex mt-8 justify-center h-screen bg-indigo-100">
  <div class="w-full max-w-lg">
    <div class="flex justify-left">
      <%= link_to 'Back to Team', team_path(@game.team), class:"bg-gray-500 hover:bg-gray-700 border-gray-500 hover:border-gray-700 text-xs border-4 text-white py-1 px-2 rounded object-right" %>
    </div>
    <div class="flex justify-center">
      <h1 class="text-lg text-blue-500 py-1 px-2">Vs. <%= @game.opponent%>, <%= @game.date%></h1> 
    </div>
      
    <div class="bg-white shadow-md px-8 pt-6 pb-8 mb-4m">
      <table class="w-full">
        <thead>
          <tr class="text-left">
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
            <% @game.team.players.each do |player| %>
              <tr class="border-b border-blue-500">
                <td class="py-5">
                  <%= player.user.first_name + " " + player.user.last_name %>
                </td>
                <td>
                  <%= link_to 'Track', game_track_path(@game, player), 'data-turbolinks' => "false", class: "bg-blue-500 hover:bg-blue-700 border-blue-500 hover:border-blue-700 text-xs border-4 text-white py-1 px-2 rounded object-right"%>
                </td>
                <td>
                  <%= link_to 'Show', game_track_show_path(@game, player), 'data-turbolinks' => "false", class: "bg-blue-500 hover:bg-blue-700 border-blue-500 hover:border-blue-700 text-xs border-4 text-white py-1 px-2 rounded object-right"%>
                </td>
              </tr>
            <% end %>
        </tbody>
    </div>
  </div>
</div>