PlayerTracker/config/routes.rb
Rails.application.routes.draw do
  resources :teams do 
    resources :settings, only: [:show]
    resources :games
    resources :players
    get '/invite', to: 'teams#invite_new'
    post '/invite', to: 'teams#invite_create'
  end
  resources :players
  resources :games do
    get '/players/:player_id/track', to: 'tracker#track', as: 'track'
    get '/players/:player_id/show', to: 'tracker#show', as: 'track_show'
  end

  post '/create_tracks', to: 'tracker#create'
  
  devise_for :users

  get 'home/index'
  root 'home#index'
end

PlayerTracker/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @teams = Team.joins(:players).where("players.user_id = ?", current_user.id)
    end
  end
end

PlayerTracker/app/helpers/home_helper.rb
module HomeHelper
end

PlayerTracker/app/views/home/index.html.erb
<div class="flex mt-8 justify-center h-screen">
  <div class="w-full max-w-lg">
    <% if current_user %>
      <div class="mt-5 max-w-md mx-auto sm:flex sm:justify-center md:mt-8">
        <div class="rounded-md">
          <%= link_to 'Create Team', new_team_path, method: 'GET', class:"btn-primary px-8 py-3 text-base leading-6 font-medium md:py-4 md:text-lg md:px-10" %>
        </div>
      </div>
      
      <% @teams.each do |team| %>
        <%= link_to team_path(team), class: "btn-team mt-4 w-full bg-white shadow-md px-8 pt-6 pb-8 mb-4m" do %>
          <span class="flex items-center font-md text-3xl text-black hover:text-primary-500 focus:outline-none focus:text-gray-900 transition duration-150 ease-in-out"><%= team.name %></span> 
        <% end %>
      <% end %>

        
    <% end %>
  </div>
</div>