PlayerTracker/config/routes.rb
Rails.application.routes.draw do
  resources :teams do 
    resources :settings, only: [:show]
    resources :games
    resources :players
    get '/invite', to: 'teams#invite_new'
    post '/invite', to: 'teams#invite_create'
  end
  resources :players
  resources :games do
    get '/players/:player_id/track', to: 'tracker#track', as: 'track'
    get '/players/:player_id/show', to: 'tracker#show', as: 'track_show'
  end

  post '/create_tracks', to: 'tracker#create'
  
  devise_for :users

  get 'home/index'
  root 'home#index'
end

PlayerTracker/app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def show
    @team = Team.find(params[:team_id])
  end
end

PlayerTracker/app/helpers/settings_helper.rb
module SettingsHelper
end

PlayerTracker/app/views/settings/show.html.erb
<div class="flex mt-8 justify-center h-screen bg-indigo-100">
  <div class="w-full max-w-6xl">
    <div class="flex w-full">
      <div class="flex w-full justify-start">
        <%= link_to 'Back to Team', team_path(@team), class:"bg-gray-500 hover:bg-gray-700 border-gray-500 hover:border-gray-700 text-xs border-4 text-white py-1 px-2 rounded object-right" %>
      </div>
    </div>
    <div class="flex justify-center">
      <h1 class="text-4xl text-blue-500 font-bold"><%= @team.name %> Settings</h1>
    </div>

    <!-- List of Players -->
    <div class="flex w-full justify-center mt-8">
      <div class="w-full mr-8">
        <div class="flex w-full mb-4">
          <h1 class="text-lg text-blue-500 py-1">Players</h1>
        </div>
        <div class="bg-white shadow-md px-8 pt-6 pb-8 mb-4m">
          <table class="w-full">
            <thead>
              <tr class="text-left">
                <th>Name</th>
              </tr>
            </thead>
            <tbody>
                <% @team.players.each do |player| %>
                  <tr class="border-b border-blue-500">
                    <td class="py-5">
                      <%= link_to player.user.first_name + " " + player.user.last_name, team_player_path(@team, player), class: "hover:text-blue-700 font-bold" %>
                    </td>
                    <td class="py-5">
                      <%= link_to 'Remove', player, method: :delete, class:"bg-red-500 hover:bg-red-700 border-red-500 hover:border-red-700 text-sm border-4 text-white py-1 px-2 rounded object-right", data: {confirm: 'Are you sure you want to remove this player?'} %>
                    </td>
                  </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>

      <!-- List of Games -->
      <div class="w-full ml-8">  
        <div class="flex w-full mb-4">
          <h1 class="text-lg text-blue-500 py-1">Games</h1>
        </div>
        <div class="bg-white shadow-md px-8 pt-6 pb-8 mb-4m">
          <table class="w-full">
            <thead>
              <tr class="text-left">
                <th>Opponent</th>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
                <% @team.games.each do |game| %>
                  <tr class="border-b border-blue-500">
                    <td class="py-5">
                      <%= link_to game.opponent, game, class: "hover:text-blue-700 font-bold" %>
                    </td>
                    <td class="py-5">
                      <%= game.date%>
                    </td>
                    <td class="py-5">
                      <%= link_to 'Remove', game, method: :delete, class:"bg-red-500 hover:bg-red-700 border-red-500 hover:border-red-700 text-sm border-4 text-white py-1 px-2 rounded object-right", data: {confirm: 'Are you sure you want to remove this game?'} %>
                    </td>
                  </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="flex w-full justify-end">
        <%= link_to 'Delete Team', @team, method: :delete, class:"bg-red-500 hover:bg-red-700 border-red-500 hover:border-red-700 text-sm border-4 text-white py-1 px-2 rounded object-right mt-8", data: {confirm: 'Are you sure you want to delete this team?'} %>
      </div>
  </div>
</div>